### ISSUE TITLE
Reorganize Code for Pip (v1.0.0)

### ISSUE THREAD

**Issue by ncc-erik-steringer** [nccgroup/PMapper#17]
Need to make this deployable with `setup.py`.

**Comment by ncc-erik-steringer** [comment]
Made progress here: 4654efedeb3b33901a42588d5850dd0e8885d29f

**Comment by kmcquade** [comment]
@ncc-erik-steringer can you also add the setup.py file to the master branch?

**Comment by ncc-erik-steringer** [comment]
@kmcquade , added an issue (#27) to track for pre-v1.

**Comment by ncc-erik-steringer** [comment]
Closing this issue, v1.0.0 is released, pre-v1 still tracked in #27.
