### ISSUE TITLE
priv_esc preset incorrect error message on missing principal

### ISSUE THREAD

**Issue by mykter** [nccgroup/PMapper#20]
**Describe the bug**
The error message when a principal isn't found says "priv_esc" can't be found, instead of the provided principal name.

**To Reproduce**
1. `$ python pmapper.py --profile securityauditor query "preset priv_esc user/doesntexist"`
`Could not find a principal matching: priv_esc`

**Expected behavior**
`Could not find a principal matching: user/doesntexist`

**Comment by ncc-erik-steringer** [comment]
Spotted the reason: https://github.com/nccgroup/PMapper/blob/master/principalmap/querying.py#L81-L85

Used wrong index for pulling tokens from the query when announcing a principal was missing. I'll aim to have it fixed by 1.0.0.

**Comment by mykter** [comment]
👍
