### ISSUE TITLE
Feature request: Skip Graph of certain Roles

### ISSUE THREAD

**Issue by kmcquade** [nccgroup/PMapper#23]
There are a few roles that we are not able to run iam:SimulatePrincipalPolicy on, due to Permissions boundaries. It would be great if we could skip graphing certain roles either by including them in an exceptions file or via CLI.

@ncc-erik-steringer

**Comment by ncc-erik-steringer** [comment]
v1.0.0 will handle this by handling all permissions simulations locally rather than calling the simulation APIs. If you want to peek at the branch v1.0.0-dev (bit stale, need to push when I get another chunk of free time), you can see that's in motion.

**Comment by kmcquade** [comment]
Noted. I'd still like to use this tool for an assessment right now though, so I'm down to use some hack-y methods if necessary (within reason).

I downloaded the v1.0.0-dev branch and executed it. Ran into a random boto error that said my STS token included in the request was invalid. (*Note*: I'm not worried about that right now, since I was able to comment all mentions of Lambda to avoid the error)

I was able to successfully run the graph function after that - but I wasn't able to run the query subcommand...

```bash
> python3 pmapper.py query preset


Traceback (most recent call last):
  File "pmapper.py", line 12, in <module>
    sys.exit(main())
  File "/Users/kmcquade/Documents/Projects/_Active/PCS/PMapper-1.0.0-dev/principalmapper/__main__.py", line 170, in main
    handle_query(parsed_args)
  File "/Users/kmcquade/Documents/Projects/_Active/PCS/PMapper-1.0.0-dev/principalmapper/__main__.py", line 216, in handle_query
    raise NotImplementedError('query subcommand is not ready for use')  # TODO: query functionality
NotImplementedError: query subcommand is not ready for use
```

Frustrated, I skimmed through the code to figure out where the data was being stored - and saw that `storage.py` stores the results in a directory with the name of the directory as the account ID, located at `~/Library/Application Support/com.nccgroup.principalmapper/123456789`. But the master branch looks for a graph _file_ at ~/.principalmap/graphfile-default, so it appears that this storage method for v1.0.0-dev is not compatible with the storage method for master. 

Am I missing something here or is there a hack-y method for reformatting the directory so I can use the master branch to leverage the data generated by the v1.0.0-dev branch?

**Comment by ncc-erik-steringer** [comment]
The new data-storage solution in v1.0.0 is not compatible with the current master branch. The new solution pulls more data (groups and policies) in order to achieve the local simulation.

To achieve your current goals, I'd suggest going back to the master branch. For a hacky solution, you can edit principalmap/enumerator.py . There's a for-loop in the method `fillOutGraph` that you can edit to exclude the names of the roles you're having issues with.

**Comment by kmcquade** [comment]
@ncc-erik-steringer - I was able to use PMapper in a different AWS account anyway, and skipped using it for the child account where I wasn't able to do it earlier. I'd still love to have this in the future, so I will leave this ticket open as a feature request. But this tool really provided us with useful results! So thank you for developing a great tool.

One suggestion - you should still leave the IAM Policy Simulator functionality in the v1.0.0 release, even though you will be permitting offline analysis / local simulation. It's powerful and very useful. 

Keep up the great work.

**Comment by ncc-erik-steringer** [comment]
Hey @kmcquade ,

The `v1.0.0-dev` branch now has full query functionality, plus a new query-handler (argquery), plus a full local policy simulator that I think is _very close_ to matching the iam:Simulate* APIs. If there is any case where the local simulator and simulator API differ, then it'll be considered a bug, fixed, and then have a test that it must pass in future releases.

I think you mentioned an STS error involving Lambda, I believe that was related to #24 and is now fixed.

For the suggestion to be able to skip certain principals during the graphing/querying process, I think that's going to end up as a won't fix. There's only so much information I can exclude before my tool basically falls apart in usefulness. If the user doesn't have the correct permissions, then there's only so much that Principal Mapper can do.

Closing.
