### ISSUE TITLE
Optimization: GetAccountAuthorizationDetails

### ISSUE THREAD

**Issue by danieladams456** [nccgroup/PMapper#26]
From [AWS blog](https://aws.amazon.com/blogs/security/a-simple-way-to-export-your-iam-settings/):
> With the `GetAccountAuthorizationDetails` API you can get a snapshot of your IAM entities with a single API call. Previously you had to use a combination of multiple API calls, some of which had to be called multiple times. With your IAM settings in one place you could use the output to monitor your intended IAM settings, store snapshots to understand differences in your IAM settings between points in time, and show IAM settings for auditing purposes.

Somehow I missed this for a long time, but it has made my code much easier.  I don't have to paginate through getting roles and connected inline policies, just do a single 10 second API call that returns 3MB of JSON.  I wonder if it would streamline things enough such that maybe enhancements like #25 would be less necessary.

It even includes instance profiles so a straight listing of ec2 describe-instances could be linked up without api call pivots.  A similar situation would work for Lambda with list-functions.

**Comment by ncc-erik-steringer** [comment]
I hadn't noticed this API before. It definitely would knock out a bunch of the work that goes into the graphing portion. The only concern I have is scaling, but the API hints that pagination is available.

**Comment by danieladams456** [comment]
Yeah, I had just been using the CLI before.  Trying it with the API it really was 13 pages.  Still not bad for 600 roles and associated policies.

**Comment by ncc-erik-steringer** [comment]
Aiming to fix this with #36 and deploy the change in the next micro version.

**Comment by ncc-erik-steringer** [comment]
Looping back around here, I think I'm gonna aim to implement this now in v1.1.0 to address #41 since the `iam:ListUsers` API ain't gonna return it.

**Comment by ncc-erik-steringer** [comment]
Completed in 5828a87b111fd10d4e1f420d41962634036e40a8 for eventual release of v1.1.0.
