### ISSUE TITLE
Validate Installation and Functionality on Target Operating Systems, Python Versions

### ISSUE THREAD

**Issue by ncc-erik-steringer** [nccgroup/PMapper#33]
Gotta make sure this tool works across multiple operating systems and Python versions. The biggest concern is the graph file-storage, since that's OS-specific code and I could only test against Ubuntu 16. 

Principal Mapper needs to be tested on the following operating systems and Python versions (but not all combinations of which):

## Python
- [x] Python 3.6
- [ ] Python 3.7 

## Operating Systems
- [ ] macOS
- [ ] Windows 10
- [x] Ubuntu 18.04
- [ ] Ubuntu Server 18.04
- [ ] Amazon Linux 2

**Comment by Kharkovlanok** [comment]
To make it sure.
I ran the tool yesterday on Ubuntu 18.04 with python 3.6 in a virtualenv. 
While I didn't get any error message when I try to get a visualization or analysis report, the script keesp running and doen't provide neither png nor text file.

I see [here](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2018/june/principal-mapper-advanced-and-automated-aws-iam-evaluation/?style=Cyber+Security), you wrote:

> It is written in Python 2 using the botocore library. We also have plans to continue development by supporting Python 3.

Can you please confirm.

**Comment by ncc-erik-steringer** [comment]
Hi @Kharkovlanok ,

That blog is outdated, thank you for drawing my attention to it. The current versions of PMapper is Python 3.5+ only. 

For the visualization/analysis bug, could you please let me know:

* The number (or approximation) of principals in the AWS account (number of IAM Roles and Users)?
* The version of Principal Mapper you're using (and if you installed via Pip or from the `master` branch)?

**Comment by Kharkovlanok** [comment]
* 4 users and approximately 200 roles
* I've used the latest version available from the master branch.

I think my issue may be related to a path error when the tool is run in a virtualenv

**Comment by ncc-erik-steringer** [comment]
Sorry for the late response!

160 nodes and 18000 edges indicates a **lot** of inter-connections, which is essentially the worst-case in terms of evaluation/visualization/querying due to the searching process (breadth-first search). It's actually pushing O(n^3) when doing queries/evaluation with all nodes with this many interconnections. This means millions and millions of IAM policy simulations. Thankfully, they're all local, but that's still tons of computation.

I'm thinking about hashing and caching the results of policy simulations to cut down on this. That should help querying/analysis. However, that's not gonna help with visualization. You might be able to create a DOT file (`--filetype` argument set to `dot`), then get a different tool to render (Gephi?) for better results.
