### ISSUE TITLE
Existence check for 'RoleARN' in stack

### ISSUE THREAD

**Issue by ancwatson** [nccgroup/PMapper#39]
**Describe the bug**
Ran into an issue where 'RoleARN' was not present within stack. 

**To Reproduce**
Ran into this when creating a new graph. Unfortunately I believe this is because of the account that I am using for enumeration.  

**Expected behavior**
It would be nice to test for the existence of 'RoleARN' within stack. I have added a fix to my local copy

https://github.com/nccgroup/PMapper/blob/2aaae80cb4f2cccec53ac9fd66d7ba764bf0364d/principalmapper/graphing/cloudformation_edges.py#L115-L120

FIX:
```
relevant_stacks = []  # we'll reuse this for *ChangeSet
                for stack in stack_list:
                    if 'RoleARN' in stack:
                        if stack['RoleARN'] == node_destination.arn:
                            relevant_stacks.append(stack)
                    else:                        
                        continue
```

**Comment by ncc-erik-steringer** [comment]
I made a bad assumption that `RoleArn` would always be present. I'll add the existence check.

**Comment by ancwatson** [comment]
No worries! Thank you!
