### ISSUE TITLE
Graphs cannot be created from AWS accounts with groups created under '/some-path/group-name'

### ISSUE THREAD

**Issue by yehuda-elementryx** [nccgroup/PMapper#50]
**Describe the bug**
If you try to create a graph for an account with a group with a path not equal to '/', the graph building process will fail.

**To Reproduce**
Steps to reproduce the behavior, please include information on suspected users/roles that are the source of the issue when possible:
1. Create a group in an AWS account with the path attribute equal to `/test/`
2. Execute `pmapper graph --create`
Wait for an error.
**Expected behavior**
The graph should succeed to be built.
** Remedy**
I'll attach a pull request to this bug report.

**Comment by ncc-erik-steringer** [comment]
Good catch, thank you.

**Comment by ncc-erik-steringer** [comment]
Merged into `master`, will bring into `v1.1.0-dev` for that release.
