### ISSUE TITLE
Offline storage/access to the data collected by PMapper

### ISSUE THREAD

**Issue by reach4bawer** [nccgroup/PMapper#59]
Is there a way to store the data in a query-able format offline. My goal is to run PMapper on multiple accounts and get access to the data collected so that I can create reports and visualizations.

I am trying to create interactive graphs for IAM roles and policies for which I need to get access to all the IAM data data offline collected for multiple accounts I was thinking of writing a script to get all the needed data when I stumbled upon this tool. Since this is much more advanced than what I wanted to do, is there a way to give access to the json files or even the objects created as part of the tool run?

**Comment by ncc-erik-steringer** [comment]
Hello there!

When you run PMapper to create a graph from an AWS account, that data is stored locally on-disk in a standard location based on your OS ( https://github.com/nccgroup/PMapper/blob/master/principalmapper/util/storage.py#L23 ). The subdirectories are the accounts that are graphed. To load a `Graph` object from what you've got on-disk, you want the class method named `create_graph_from_local_disk` ( https://github.com/nccgroup/PMapper/blob/master/principalmapper/common/graphs.py#L107 ). 

That source code + comments should hopefully be enough for you to get started with what you want to do, but please let me know if you have any other questions.
