### ISSUE TITLE
Using python 2.7.16 which is now deprecated. Can this be updated to use Python 3 please?

### ISSUE THREAD

**Issue by cappellem** [nccgroup/PMapper#63]
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Processing /Users/mvandecappelle/tools/PMapper
ERROR: Package 'principalmapper' requires a different Python: 2.7.16 not in '>=3.5, <4'

**Comment by ncc-erik-steringer** [comment]
Hi there!

Looks like you're trying to install PMapper from `pip` using Python 2. Unfortunately PMapper now requires Python 3 for installation.

**Comment by cappellem** [comment]
👍
