### ISSUE TITLE
Secrets Manager Support

### ISSUE THREAD

**Issue by ncc-erik-steringer** [nccgroup/PMapper#75]
Need to pull/cache resource policies for Secrets Manager.

**Comment by nxtof** [comment]
This would be super useful. :-)

**Comment by ncc-erik-steringer** [comment]
Done in v1.1.2-dev, commit cdfd66b936057a9cc950d0f008cd32554c55ac4f

**Comment by nxtof** [comment]
Very nice! Seems to be working like a charm for me.

**Comment by ncc-erik-steringer** [comment]
Closing to mark progress towards v1.1.2.
