### ISSUE TITLE
where's the `org_update` subcommand

### ISSUE THREAD

**Issue by klauern** [nccgroup/PMapper#76]
**Question**

Just recently upgraded to 1.1.0 of pmapper and was trying it out.  I got a lot of errors like this:

```
 Unable to load a Graph object for account 12345678912, possibly because it is not mapped yet. Please map all accounts and then update the Organization Tree (`pmapper graph org_update`).
```

except I think that has been removed.  I did run `pmapper org create` with the management account profile, but I'm not sure if there's a way to take the one and perform work for the other or not.

**Did the Wiki Have an Answer?**

**Comment by ncc-erik-steringer** [comment]
Hi there,

I goofed. The sub-subcommand is `orgs update` ( https://github.com/nccgroup/PMapper/wiki/CLI-Reference#orgs-update ). I'll update this string for v1.1.1.

**Comment by ncc-erik-steringer** [comment]
v1.1.1 is out and these references are updated within, thank you!
