### ISSUE TITLE
Does PMapper support cross-account graphing, querying, and analysis?

### ISSUE THREAD

**Issue by mdb-vzeddie** [nccgroup/PMapper#88]
**Question**

Does PMapper support cross-account graphing, querying, and analysis?

**Wiki**

https://github.com/nccgroup/PMapper/wiki does not have an answer. I suggest putting it in the FAQ section or create a new section about cross-account architecture. 

-----

If a role in account A can assume a role in account B, can this be caught by PMapper? What does the CLI syntax look like to analyze for such scenarios?

**Comment by ncc-erik-steringer** [comment]
Mostly!

Right now cross-account querying is not available via CLI, we need to figure out how to gracefully allow that type of query. If your accounts are all under an AWS Organization, you can use `pmapper orgs update` after you finish graphing the accounts, and it'll print a list of inter-account edges.

There are library functions that handle generating cross-account edges between two arbitrary graphs (no organizations link required) as well as running queries against multiple accounts:

* https://github.com/nccgroup/PMapper/blob/722efec4f7c89a5a440facd8a5bd055c88db7194/principalmapper/graphing/cross_account_edges.py#L29
* https://github.com/nccgroup/PMapper/blob/722efec4f7c89a5a440facd8a5bd055c88db7194/principalmapper/querying/query_interface.py#L89
* https://github.com/nccgroup/PMapper/blob/722efec4f7c89a5a440facd8a5bd055c88db7194/principalmapper/querying/query_utils.py#L226

Good call on updating the wiki for cross-account work. I'll leave this issue open until I knock that out.

**Comment by ncc-erik-steringer** [comment]
Wiki updated: https://github.com/nccgroup/PMapper/wiki/Frequently-Asked-Questions#how-do-i-do-cross-account-authorization-checks

Thank you!
