### ISSUE TITLE
اوكي

### ISSUE THREAD

**Issue by boulkroune** [nccgroup/PMapper#91]
**Brief Description**

**IAM Action, Resource, and Condition Being Authorized**
The Action, Resource(s), and Condition(s) of the API call being authorized.

**IAM Policies Attached to Principal**
The IAM Policies attached to the principal making the API call being authorized. If possible, reduce the involved 
policies to the bare minimum statement(s) that still reproduce the issue.

**Expected Behavior**
Whether or not the API call should be authorized.

**AWS IAM Policy Simulation Result**
If possible, run the request parameters through AWS' IAM Policy Simulator (<https://policysim.aws.amazon.com/>) and report the result.

**Comment by ncc-erik-steringer** [comment]
مرحبا هل لديك سؤال؟
